# Generated by Django 5.0.4 on 2024-08-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
