# Generated by Django 5.0.4 on 2024-08-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_pic',
            field=models.ImageField(blank=True, null=True, upload_to='books/cover_pics/'),
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='books/pdf_files/'),
        ),
    ]
